defmodule ExDisposable.BlocklistUpdater do
  @moduledoc false
  @compile {:no_warn_undefined, {:httpc, 4}}

  @blocklist_url "https://raw.githubusercontent.com/disposable-email-domains/disposable-email-domains/refs/heads/main/disposable_email_blocklist.conf"
  @blocklist_path Path.join(["priv", "disposable_email_blocklist.conf"])
  @mix_exs_path "mix.exs"
  @version_pattern ~r/version:\s*"(?<version>\d+\.\d+\.\d+)"/

  def blocklist_path do
    @blocklist_path
  end

  def mix_exs_path do
    @mix_exs_path
  end

  def download_blocklist do
    with :ok <- ensure_http_client_started(),
         {:ok, {{_http_version, 200, _reason_phrase}, _headers, response_body}} <-
           :httpc.request(:get, {String.to_charlist(@blocklist_url), []}, [],
             body_format: :binary
           ) do
      {:ok, response_body}
    else
      {:ok, {{_http_version, status_code, reason_phrase}, _headers, _response_body}} ->
        {:error, "Failed to download blocklist: HTTP #{status_code} #{to_string(reason_phrase)}"}

      {:error, reason} ->
        {:error, "Failed to download blocklist: #{format_error(reason)}"}
    end
  end

  def current_blocklist_contents(blocklist_path \\ @blocklist_path) do
    case File.read(blocklist_path) do
      {:ok, blocklist_contents} ->
        {:ok, blocklist_contents}

      {:error, :enoent} ->
        {:ok, nil}

      {:error, reason} ->
        {:error, "Failed to read #{blocklist_path}: #{:file.format_error(reason)}"}
    end
  end

  def blocklist_changed?(downloaded_blocklist_contents, existing_blocklist_contents) do
    downloaded_blocklist_contents != existing_blocklist_contents
  end

  def branch_name(date \\ Date.utc_today()) do
    "blocklist-update-#{Date.to_iso8601(date)}"
  end

  def commit_title(date \\ Date.utc_today()) do
    "Update disposable email blocklist (#{Date.to_iso8601(date)})"
  end

  def pull_request_body(date, version) do
    """
    ## Summary

    - update `#{@blocklist_path}` from upstream
    - bump the library version to `#{version}`
    - generated by `mix ex_disposable.sync_blocklist` on #{Date.to_iso8601(date)}
    """
  end

  def update_mix_exs_version(mix_exs_contents) do
    with {:ok, current_version} <- extract_version(mix_exs_contents),
         {:ok, updated_version} <- bump_patch_version(current_version) do
      updated_mix_exs_contents =
        Regex.replace(
          @version_pattern,
          mix_exs_contents,
          ~s(version: "#{updated_version}"),
          global: false
        )

      {:ok, updated_mix_exs_contents, current_version, updated_version}
    end
  end

  def bump_patch_version(version) do
    case String.split(version, ".") do
      [major_segment, minor_segment, patch_segment] ->
        case Integer.parse(patch_segment) do
          {patch_number, ""} ->
            {:ok,
             Enum.join([major_segment, minor_segment, Integer.to_string(patch_number + 1)], ".")}

          _other ->
            {:error, "Unsupported version format: #{version}"}
        end

      _other ->
        {:error, "Unsupported version format: #{version}"}
    end
  end

  defp extract_version(mix_exs_contents) do
    case Regex.named_captures(@version_pattern, mix_exs_contents) do
      %{"version" => version} ->
        {:ok, version}

      _other ->
        {:error, "Could not find the project version in #{@mix_exs_path}"}
    end
  end

  defp ensure_http_client_started do
    case Application.ensure_all_started(:inets) do
      {:ok, _applications} ->
        ensure_ssl_started()

      {:error, reason} ->
        {:error, "Failed to start :inets: #{inspect(reason)}"}
    end
  end

  defp ensure_ssl_started do
    case Application.ensure_all_started(:ssl) do
      {:ok, _applications} ->
        :ok

      {:error, reason} ->
        {:error, "Failed to start :ssl: #{inspect(reason)}"}
    end
  end

  defp format_error(reason) when is_atom(reason) do
    Atom.to_string(reason)
  end

  defp format_error(reason) do
    inspect(reason)
  end
end
